apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: {{ .Values.product.replicaCount }}

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: {{ .Values.product.image }}
          # imagePullPolicy: Never
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.product.servicePort }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.product.servicePort }}

            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.product.servicePort }}

            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"
            