product:
  # image: product-service:v2
  image: 069481747467.dkr.ecr.ap-south-1.amazonaws.com/product-service:v1
  replicaCount: 1
  servicePort: 8080

order:
  # image: order-service:v2
  image: 069481747467.dkr.ecr.ap-south-1.amazonaws.com/order-service:v1
  replicaCount: 1
  servicePort: 8081

